version: '3'

services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  database:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  database-data: