version: '3'

services:
  app:
    build: .
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  database:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
